log_dir: ThrustOmega_model/1027vvvvv/ppo_F450_rot_spinz_pos_vel_01_01_102_05_baseself0815_0623_motor0.15_default/seed_002/
n_parallel: 1
plot: false
seed: 2
snapshot_mode: last
variant:
  alg_class: PPO
  alg_param:
    batch_size: 28000
    clip_range: 0.05
    discount: 0.99
    max_path_length: 700
    max_samples: 10000000000
    n_itr: 9002
    optimizer_args:
      batch_size: 128
      max_epochs: 20
    play_every_itr: null
    plot: false
    record_every_itr: 100
    step_size: 0.01
    store_paths: false
  baseline_class: GaussianMLPBaseline
  baseline_param: {}
  env: QuadrotorEnv
  env_param:
    dynamics_change:
      damp:
        omega_quadratic: 0.0
        vel: 0.0
      noise:
        thrust_noise_ratio: 0.05
    dynamics_params: F450
    ep_time: 7
    init_random_state: true
    obs_repr: xyz_vxyz_rot_omega
    raw_control: ThrustOmga
    rew_coeff:
      action_change: 0.0
      attitude: 0.0
      crash: 1.0
      effort: 1.0
      omega: 0.1
      orient: 1.0
      pos: 1.02
      pos_linear_weight: 1.0
      pos_log_weight: 0.0
      rot: 0.1
      spin: 0.1
      spin_z: 0.1
      vel: 0.3
      yaw: 2.5
    reward_type: sou
    sense_noise: self_define
    sim_freq: 200
    sim_steps: 2
  policy_class: GaussianMLPPolicy
  policy_param:
    hidden_sizes:
    - 64
    - 64
